In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("magic.csv", header=None)

In [3]:
dataset

0         1       2       3       4         5         6   \
0       28.7967   16.0021  2.6449  0.3918  0.1982   27.7004   22.0110   
1       31.6036   11.7235  2.5185  0.5303  0.3773   26.2722   23.8238   
2      162.0520  136.0310  4.0612  0.0374  0.0187  116.7410  -64.8580   
3       23.8172    9.5728  2.3385  0.6147  0.3922   27.2107   -6.4633   
4       75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277   28.5525   
5       51.6240   21.1502  2.9085  0.2420  0.1340   50.8761   43.1887   
6       48.2468   17.3565  3.0332  0.2529  0.1515    8.5730   38.0957   
7       26.7897   13.7595  2.5521  0.4236  0.2174   29.6339   20.4560   
8       96.2327   46.5165  4.1540  0.0779  0.0390  110.3550   85.0486   
9       46.7619   15.1993  2.5786  0.3377  0.1913   24.7548   43.8771   
10      62.7766   29.9104  3.3331  0.2475  0.1261  -33.9065   57.5848   
11      18.8562   16.4600  2.4385  0.5282  0.2933   25.1269   -6.5401   
12      45.6321   22.7100  3.0441  0.2213  0.1215  -18.3986  -20.6427   
13      33.1818   12.4655  2.4955  0.4696  0.2412  -17.0341  -22.0762   
14      60.4580   33.1061  3.1944  0.4679  0.2464   14.3000  -33.8765   
15      29.4741   22.4581  2.6258  0.3077  0.1740   18.1242   22.7035   
16      36.1741   17.6865  2.9460  0.2865  0.1591   -4.7746  -18.9697   
17      46.2915   16.0328  2.7756  0.3403  0.1920   49.9706   33.3653   
18      46.0588   18.7870  3.2217  0.2431  0.1504   49.2704   34.1066   
19      44.7394   15.6364  2.6380  0.3107  0.1715   14.0430   37.2246   
20      91.6423   71.8818  3.8484  0.0780  0.0430  -56.7107   72.3016   
21      86.0486   21.8287  3.3587  0.2369  0.1662  -58.7854   57.8212   
22      90.5299   17.8721  3.0330  0.2122  0.1080  -57.4170   84.6189   
23      20.3836    9.0462  2.3365  0.6359  0.3894   22.2700   12.9487   
24      87.2384   27.9350  2.8848  0.3155  0.1806  -18.2102   66.6867   
25     107.3380   29.1356  3.5265  0.1315  0.0683  -47.1175   89.5136   
26      27.2304   19.2817  2.6375  0.3710  0.2039   23.0406   23.3428   
27      26.7065   18.9070  2.6781  0.4281  0.2214    9.1616   18.6858   
28      23.5647    9.9926  2.2095  0.5679  0.3364   30.0056  -13.8665   
29      34.7486   19.2286  2.5629  0.3666  0.1984   30.3637  -16.3092   
...         ...       ...     ...     ...     ...       ...       ...   
18990   26.0277    7.4010  2.4223  0.6194  0.3791  -27.8670   14.0382   
18991   32.1547   12.5410  2.7593  0.4317  0.2167   31.6221   24.5785   
18992  169.0402   35.3614  3.2894  0.3349  0.1986 -162.2329   70.4636   
18993   18.8377    8.8786  2.5617  0.6039  0.3234    0.4589   15.5433   
18994  195.2309   67.0206  3.7669  0.1195  0.0677 -119.1863 -155.8811   
18995   67.7139   28.5831  3.2384  0.2050  0.1106 -133.6450   63.1391   
18996   29.8353   11.3519  2.4449  0.4890  0.2948    9.9236   -9.0429   
18997   18.0124   10.6746  2.5694  0.5768  0.2951  -23.3968   -9.2150   
18998  207.2530   75.8327  4.1476  0.0739  0.0371 -242.4960 -180.0290   
18999  172.2442   20.1926  2.9009  0.2887  0.1940  124.5990  112.9452   
19000   69.3556   31.9822  3.2231  0.3093  0.1744  -52.6569  -42.0622   
19001   57.1905   35.5095  2.7177  0.2337  0.1197  -48.5112  -54.2835   
19002  110.7140   26.8312  3.2212  0.1856  0.1247 -158.0625   73.2259   
19003   21.5189   15.4205  2.7328  0.5587  0.3117   -7.3668    9.2409   
19004   23.4293   11.3673  2.7001  0.3842  0.1890  -26.3784  -14.5363   
19005   23.8277   11.8989  2.4393  0.4655  0.2891   11.1013   11.5776   
19006   32.1454   13.8296  2.4844  0.5182  0.2761  -36.0633  -15.9648   
19007  115.2640   14.0075  2.8540  0.7544  0.4136  -88.2076 -117.4860   
19008  133.4950   40.1631  3.3050  0.1169  0.0602   84.1711  -81.3323   
19009   39.5223   18.6327  2.8341  0.2462  0.1414   24.1819   23.2190   
19010   32.4902   10.6723  2.4742  0.4664  0.2735  -27.0097  -21.1687   
19011   79.5528   44.9929  3.5488  0.1656  0.0900  -39.6213   53.7866   
19012   31.8373   13.8734  2.8251  0.4169  0.1988  -16.4919  -27.1448  

In [4]:
X = dataset.iloc[:, 0:10].values
y = dataset.iloc[:, 10].values

In [5]:
y

array(['g', 'g', 'g', ..., 'h', 'h', 'h'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
label_y = LabelEncoder()
y = label_y.fit_transform(y)

In [7]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Activation

Using TensorFlow backend.


In [11]:
classifier = Sequential()
classifier.add(Dense(64, input_dim=10, kernel_initializer='uniform', activation='tanh'))
classifier.add(Dense(64, kernel_initializer='uniform', activation='tanh'))
classifier.add(Dense(64, kernel_initializer='uniform', activation='softmax'))
classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
classifier.compile('adam', 'binary_crossentropy', ['accuracy'])

In [12]:
classifier.fit(X_train, y_train, batch_size=16, epochs=70)

Epoch 1/70
15216/15216 [==============================] - 1s 81us/step - loss: 0.5688 - acc: 0.7725
Epoch 2/70
15216/15216 [==============================] - 1s 60us/step - loss: 0.4980 - acc: 0.7925
Epoch 3/70
15216/15216 [==============================] - 1s 61us/step - loss: 0.4538 - acc: 0.8173
Epoch 4/70
15216/15216 [==============================] - 1s 60us/step - loss: 0.4143 - acc: 0.8380
Epoch 5/70
15216/15216 [==============================] - 1s 64us/step - loss: 0.3928 - acc: 0.8396
Epoch 6/70
15216/15216 [==============================] - 1s 66us/step - loss: 0.3841 - acc: 0.8400
Epoch 7/70
15216/15216 [==============================] - 1s 60us/step - loss: 0.3780 - acc: 0.8400
Epoch 8/70
15216/15216 [==============================] - 1s 61us/step - loss: 0.3737 - acc: 0.8401
Epoch 9/70
15216/15216 [==============================] - 1s 60us/step - loss: 0.3710 - acc: 0.8444
Epoch 10/70
15216/15216 [==============================] - 1s 61us/step - loss: 0.3663 - acc: 0.8451

In [13]:
y_pred = classifier.predict(X_test, batch_size=16)

In [14]:
y_pred = (y_pred > 0.5)

In [15]:
y_pred

array([[ True],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [ True]], dtype=bool)

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2314,  146],
       [ 307, 1037]])

In [18]:
TP, FP, FN, TN = cm[0][0], cm[0][1], cm[1][0], cm[1][1]

ACC = (TP + TN)/(TP+FP+FN+TN)
PPV = TP/(TP+FP)
TPR = TP/(TP+FN)
F1 = (PPV*TPR)/(PPV+TPR)

In [19]:
def percent(value):
    return "{0:.0%}".format(value)

In [20]:
import csv 

name = "result.csv"
with open(name, 'w') as file:
    writer = csv.writer(file)
    titles = ['True Positives', 'False Positives', 'False Negatives', 
              'True Negatives', 'Accuracy', 'Precision', 'Sensitivity',
             'F1']
    writer.writerow(titles)
    values = [TP, FP, FN, TN, percent(ACC), percent(PPV), percent(TPR), percent(F1)]   
    writer.writerow(values)

In [21]:
total_summary = pd.read_csv('result.csv')
total_summary

True Positives  False Positives  False Negatives  True Negatives Accuracy  \
0            2314              146              307            1037      88%   

  Precision Sensitivity   F1  
0       94%         88%  46%

In [22]:
y_pred = np.reshape(y_pred, (np.product(y_pred.shape),))

In [23]:
print("Accuracy: {0:.0f}%".format((list(y_test-y_pred).count(0)/len(y_test))*100))
print(classifier.summary())

Accuracy: 88%
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                704       
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_3 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 65        
Total params: 9,089
Trainable params: 9,089
Non-trainable params: 0
_________________________________________________________________
None
